apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stage-lh-practice-api
commonLabels:
  app: deploylhpracticeapi
resources:
  - lh-practice-cm.yaml
  - lh-practice-sec.yaml
  - ../../../base/apps/api/lh-practice-api
  - hpa.yaml
  - ingress-api.yaml
patchesStrategicMerge:
  - deployment.yaml
patchesJson6902:
- target:
    version: v1
    kind: Deployment
    name: deploylhpracticeapi
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/name
      value: deploylhpracticeapi
- target:
    version: v1
    kind: Ingress
    name: ingresslhpracticeapi
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: staging-api.linear.health
    - op: replace
      path: /spec/rules/0/http/paths/0/backend/service/name
      value: servicelhpracticeapi
images:
- name: 052758603943.dkr.ecr.us-east-2.amazonaws.com/lh-practice-api-stage
  newTag: '1'