apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stage-lh-bh-assessment-api
commonLabels:
  app: deploylhbhassessmentapi
resources:
  - lh-bh-assessment-cm.yaml
  - lh-bh-assessment-sec.yaml
  - ../../../base/apps/api/lh-bh-assessment-api
  - hpa.yaml
  - ingress-api.yaml
patchesStrategicMerge:
  - deployment.yaml
patchesJson6902:
- target:
    version: v1
    kind: Deployment
    name: deploylhbhassessmentapi
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/name
      value: deploylhbhassessmentapi
- target:
    version: v1
    kind: Ingress
    name: ingresslhbhassessmentapi
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: staging-api.linear.health
    - op: replace
      path: /spec/rules/0/http/paths/0/backend/service/name
      value: servicelhbhassessmentapi
images:
- name: 052758603943.dkr.ecr.us-east-2.amazonaws.com/lh-bh-assessment-api-stage
  newTag: '1'
