apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
  name: hpalheformsapi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploylheformsapi
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60